### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Sqm-suks-dont-go** [MohrJonas/obsidian-matrix#1]
Just want to start of by saying this is a great plugin. had a couple ideas for enhancements.

1. Would be nice if i would specify the type of latex matrix for example a bmatrix instead of a pmatrix
2. Would be nice if i would use the keyboard to navigate to different between column and row elements in the drop down window instead of clicking each element

**Comment by MohrJonas** [comment]
Thank you for your enhancement ideas. The ability to select the matrix type is now added as of commit [5f7425d](https://github.com/MohrJonas/obsidian-matrix/commit/5f7425dfe704698372f0968f99e4fbe015dabd22).
Keyboard navigation, however, is already possible by using the *Tab* key.
Hope that helps 😀

**Comment by MohrJonas** [comment]
Merged as of obsidian-matrix version 1.1.0. Simply updating the plugin from the community plugins should do the trick.

**Comment by Sqm-suks-dont-go** [comment]
Works Great! Thank you.
